import { Global, css } from "@emotion/react";
import clsx from "clsx";
// import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin", "greek"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function BasicLayout({ children }: { children: React.ReactNode }) {
  return (
    <div
      className={clsx(
        inter.className,
        "w-full min-h-full flex flex-col flex-1 text-[16px] bg-gray-100",
      )}
    >
      <Global
        styles={css`
          ul,
          li {
            margin: 0;
            padding: 0;
          }
        `}
      />
      {children}
    </div>
  );
}
