name: Building
description: Build all packages

runs:
  using: composite
  steps:
    - name: Build (harnica-lib)
      shell: bash
      working-directory: ./pkgs/harnica-lib
      run: |
        pwd
        yarn build

    - name: Build (web)
      shell: bash
      working-directory: ./pkgs/web
      run: |
        pwd
        yarn build
