name: Building
description: Build all packages

runs:
  using: composite
  steps:
    - name: Build (harnica-midi)
      shell: bash
      working-directory: ./pkgs/harnica-midi
      run: |
        pwd
        yarn build

    - name: Build (web)
      shell: bash
      working-directory: ./pkgs/web
      run: |
        pwd
        yarn build
